Make still fragment
paulrozhkin/tamagotch-android-client pull request #8
Opened 2020-06-01 22:00 UTC by ForsaiR

2020-06-01 22:03 UTC, ForsaiR commented
Занесена новая партия багов.  Фиксить буду чуть позже. По сути, все почти адекватно работает, не скажу что красиво, но пойдет.

2020-06-02 00:32 UTC, paulrozhkin commented
В целом, для первого тыканья backend приложения, нормально.

2020-06-02 00:38 UTC, paulrozhkin requested changes

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/FeedbackRepository.java
> +        return Single.create(source ->
Откуда взялась 404? Да и в целом зачем тут новый Single создавать для обработки нахрен не нужных ошибок, можно просто вернуть первичный из либы

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/main/MainViewModel.java
> +                        RuntimeException::new
При неудачном обновлении приложение падает, не надо так

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/main/MainViewModel.java
> +    public void refreshCurrentUser() {
Не очень удачное имя. По идее это update

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/UsersRepository.java
> +    public Single<List<UserModel>> getUsers() {
Так а зачем вообще было добавлять этот метод, если возврат null

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/slidingpanel/SlidingPanelStillAboutMe.java
> +        EditText editText = slidingPanelStillAboutMe.findViewById(R.id.editTextUserName);
Вынести в поле класса

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/still/StillFragment.java
> +                textView.setText(user.getFullName());
А давай тут ставить логин, если отсутствует имя

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/still/StillFragment.java
> +            viewModel.setSelectedOrder(order);
А зачем нам вообще нужно хранить выбранный заказ во viewmodel? В приложении персонала на основе этого происходит открытие подробной инфы по заказу, а тут?

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/still/StillFragment.java
> +        viewModel.refreshOrders();
Так выходит, что оно не обновляется в риалтайме. Только при создании этого фрагмента заново.

2020-06-02 00:38 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/ui/main/MainViewModel.java
> +        completedOrdersSubscriber = getAllUserOrders()
Так мы отображаем все заказы пользователя, а не только активные?

2020-06-03 11:47 UTC, ForsaiR commented
Исправил, можешь проводить review.

2020-06-03 12:23 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/UsersRepository.java
> +        return Single.create(source ->
Тут тоже single.create убери

2020-06-03 12:23 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/UsersRepository.java
> +        );
Убрать single.create

2020-06-03 12:23 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/FeedbackRepository.java
> +    public Single<List<FeedbackModel>> getFeedback() {
Это клиентское приложение, не надо сюда пихать фичи, доступные только персоналу ресторана

2020-06-03 12:23 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/UsersRepository.java
> +    public Single<List<UserModel>> getUsers() {
Это клиентское приложение, не надо сюда пихать фичи, доступные только персоналу ресторана

2020-06-03 12:23 UTC, paulrozhkin commented on app/src/main/java/com/tamagotchi/restaurantclientapplication/data/repositories/FeedbackRepository.java
> +    public Single<List<FeedbackModel>> getFeedback() {
Удали вообще

2020-06-03 12:24 UTC, paulrozhkin approved these changes

2020-06-03 12:25 UTC, merged